### ISSUE TITLE
ZabbixSender and UTF LLD

### ISSUE THREAD

**Issue by viktorkho** [blacked/py-zabbix#28]
I'm trying to find proper way to send LLD JSON-data to Zabbix Server, but still without result.
If I use UTF-symbols in Macro's value, Zabbix Servers disables lld-item with "Value should be a JSON object" error. (I tried a lot of `u"XXX"`, `*.encode`, `*.decode` combinations)
Does anybody have some ideas how to change next pease of code to make it works?
```
# -*- coding: utf-8 -*-
...
sys.setdefaultencoding('UTF8')
...
data = '{"data": [{"{#ID}": "28502", "{#DESCRIPTION}": "Й"}]}'
zm = ZabbixMetric(host, zkey, data)
result = ZabbixSender(nocs).send([zm])
```

**Comment by maksim77** [comment]
Wait a second. Why did you decide that this data is even possible to send via zabbix sender? 
These are two completely different standards and they are sent in the JSON documents are different.

Besides, I'm not quite sure that LLD data can be sent this way. If I'm not confused Zabbix the server itself runs the scripts LLD and waits for a reply of the result of their work.

**Comment by blacked** [comment]
I think you can send this data, but it zabbix server will convert it to ascii also.

**Comment by maksim77** [comment]
OK. I realized where I was wrong.
I'll have to try on my server.

**Comment by maksim77** [comment]
@viktorkho please check the solution from ref#28-fix-utf8:
```bash
$ git clone https://github.com/blacked/py-zabbix.git
$ cd py-zabbix/
$ git checkout ref#28-fix-utf8
$ python setup.py install
```
I recommend to install this version in a virtualenv environment, so as not to affect the whole system.

I can say that I have it up and running :). In any case, your example worked without error.
![2016-03-24 18 18 21](https://cloud.githubusercontent.com/assets/155911/14021517/daf217be-f1ec-11e5-8971-6a46808219bc.png)

**Comment by blacked** [comment]
https://github.com/blacked/py-zabbix/pull/58
