### ISSUE TITLE
Zabbix 3.0.1. The "apiinfo.version" method must be called without the "auth" parameter.

### ISSUE THREAD

**Issue by Prototype-X** [blacked/py-zabbix#34]
Hi
python 3.4.3
Zabbix 3.0.1
Install py-zabbix from pypi.

`from pyzabbix import ZabbixAPI`
`zbx_api = ZabbixAPI(url='https://zabbix.example.ru', use_authenticate=False, user='admin', password='admin')`
`zbx_api.api_version()`

File "test.py", line 15, in main
    zbx_api.api_version()
  File "/pyzabbix/api.py", line 162, in api_version
    return self.apiinfo.version()
  File "/pyzabbix/api.py", line 82, in fn
    args or kwargs
  File "/pyzabbix/api.py", line 229, in do_request
    raise ZabbixAPIException(msg, err['code'])
pyzabbix.api.ZabbixAPIException: ('Error -32602: Invalid params., The "apiinfo.version" method must be called without the "auth" parameter. while sending {\'params\': {}, \'auth\': \'f1c7dce7a38cd8055a07da18ef6d5671\', \'jsonrpc\': \'2.0\', \'method\': \'apiinfo.version\', \'id\': \'1\'}', -32602)

**Comment by blacked** [comment]
https://github.com/blacked/py-zabbix/pull/36
