### ISSUE TITLE
get_id() not work with map object

### ISSUE THREAD

**Issue by Prototype-X** [blacked/py-zabbix#46]
zbx_api.get_id(item_type='map', item='Mymap')

    print(zbx_api.get_id(item_type='map', item='Mymap'))
  File "/py3-venv/lib/python3.4/site-packages/pyzabbix/api.py", line 333, in get_id
    result.append(int(obj.get(item_id)))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by blacked** [comment]
https://github.com/blacked/py-zabbix/pull/52
