### ISSUE TITLE
Error with urllib2.urlopen on Debian Jessie and Python < 3.4.3

### ISSUE THREAD

**Issue by dlgg** [blacked/py-zabbix#49]
Hi

We cannot connect to a zabbix server from our script on Debian 8 which used Python 3.4.2.
Regarding this https://docs.python.org/3/library/urllib.request.html#module-urllib.request, the context option is added in 3.4.3 and api.py manage only adding context in 2.7.9 (near line 215 on master branches).
Could you add a case where context is added only for 3.4.3 and later ? 

Regards

**Comment by blacked** [comment]
https://github.com/blacked/py-zabbix/pull/52
