### ISSUE TITLE
Zabbix exception on auth attempt

### ISSUE THREAD

**Issue by rbberry** [blacked/py-zabbix#5]
Receive following error when attempting to auth against Zabbix with username + password:

ZabbixAPIException: ('Error -32602: Invalid params., The "user.login" method must be called without the "auth" parameter

Seems like the login request uses the same do_request method as all other requests, which include this auth parameter. This is invalid in user.login requests, at least with Zabbix 2.4.1

**Comment by blacked** [comment]
https://github.com/blacked/py-zabbix/pull/36
