### ISSUE TITLE
Connecto to API via HTTP proxy

### ISSUE THREAD

**Issue by smarmie** [blacked/py-zabbix#62]
Hi,

Any way to connect to the Zabbix API using a HTTP proxy?

Thanks.

**Comment by maksim77** [comment]
Hi!
We use the [urllib](https://docs.python.org/2/library/urllib2.html) library. According to its documentation in case of detection of an environment variable like `*_proxy` (e.g. `http_proxy` or `https_proxy`) will be used when the query is executed.

**Comment by smarmie** [comment]
Excellent. Thanks also for the quick reaction.
